name = "income-empire"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "income-empire"
database_id = "YOUR_DB_ID"

[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_ID"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "income-files"

[vars]
STRIPE_KEY = "sk_live_YOUR_KEY"
OPENAI_KEY = "sk-YOUR_KEY"

[[durable_objects.bindings]]
name = "JOB_PROCESSOR"
class_name = "JobProcessor"

[[durable_objects.bindings]]
name = "PAYMENT_PROCESSOR"
class_name = "PaymentProcessor"

[[migrations]]
tag = "v1"
new_classes = ["JobProcessor", "PaymentProcessor"]