name = "real-income-system"
main = "src/real-income.js"
compatibility_date = "2023-10-30"

# Simple, clean configuration for REAL income opportunities
[env.production.vars]
ENVIRONMENT = "production"
SYSTEM_TYPE = "real_income_opportunities"