name = "first-dollar-mission"
main = "first-dollar-worker.js"
compatibility_date = "2024-01-01"

# KV namespace for earnings tracking (will be created during deployment)
[[kv_namespaces]]
binding = "KV"
id = "first_dollar_kv"
preview_id = "first_dollar_kv_preview"

# Environment variables
[vars]
MISSION_NAME = "First $5 to Cloudflare Pro"
TARGET_EARNINGS = "5.00"

# Development settings
[dev]
port = 8787
local_protocol = "http"