name = "sina-escrow-empire"
main = "src/escrow-to-scale-worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
ENVIRONMENT = "production"
SYSTEM_MODE = "ESCROW_TO_SCALE"

[[d1_databases]]
binding = "D1"
database_name = "escrow-db"
database_id = "create-escrow-db-id-here"

[[kv_namespaces]]
binding = "KV"
id = "create-escrow-kv-id-here"
