name = "sina-empire-revenue-multiplier"
main = "src/index.js"
compatibility_date = "2025-09-20"

# Cron triggers for auto-scaling and Pro-purchase checks
[triggers]
crons = ["*/5 * * * *"]

# KV Namespace Bindings
kv_namespaces = [
  { binding = "EARNINGS_KV", id = "9ca5fa02e54a4ec3b0e77243ba842608" },
  { binding = "EMPIRE_CACHE", id = "1164fb667ae0464898de97d1f563886d" },
  { binding = "EMPIRE_CONTEXT", id = "36117b73cef941659257140e7066b5f7" },
  { binding = "SINA_CACHE", id = "cf19a78186ad42aba2bb76d7b34de672" },
  { binding = "SINA_EMPIRE_KV", id = "09aae939bc894cf1a15220fe828865f2" },
  { binding = "AUTOMATION_KV", id = "4d77c10ba1354134b6802a2de55f52f8" },
  { binding = "WEBHOOKS_KV", id = "3bbcd308d5b445e7bac902c55306ad3a" },
  { binding = "SECURITY_POLICIES", id = "0fef29570fca4fec977c43f33a856666" },
  { binding = "API_KEYS", id = "2b06bf375a9e4e82931a55f1a5fb6aff" },
  { binding = "MONITORING_CACHE", id = "34acb1e1a4a845c7931e8a6c67cd7344" },
  { binding = "ORCHESTRATOR_STATE", id = "1d1359f07ebf484e858d42445149be74" },
  { binding = "DEPLOYMENT_META", id = "5a8e7f12fa8e4868b72c9e5a03f6c04c" },
  { binding = "STRIPE_CONFIG", id = "8e96840961cb4a35b60425997d299cda" },
  { binding = "STRIPE_CACHE", id = "a8671847d0b147a3b897caac2a39c05e" },
  { binding = "VOICE_STORAGE", id = "7af1a98ea8054237af880f3bb7d5248f" },
  { binding = "AI_SESSIONS", id = "a962fb6328dc4e3ca4950ada17a5bc3d" },
  { binding = "CLAUDE_SESSIONS", id = "c87f7299cfae4bd08e54dcfab3d473e2" },
  { binding = "GEMINI_SESSIONS", id = "ba0452110d274dd19d4b32b2f20c0914" },
  { binding = "SUPPLIER_INTEL", id = "5c60237afd5f4b9bacb84d5be8a6d588" },
  { binding = "GENEALOGY_DATA", id = "59694d39d35e47f398f5cc3db8d35d80" }
]

# D1 Database Bindings
[[d1_databases]]
binding = "MAIN_HUB_DB"
database_name = "sina-empire-master-hub"
database_id = "f8c2d087-2232-420d-be02-9388e5f5ea60"

[[d1_databases]]
binding = "CASHFLOW_DB"
database_name = "sina-empire-cashflow"
database_id = "718ce63c-1063-4684-9898-cb6668e25c97"

[[d1_databases]]
binding = "ORCHESTRATOR_DB"
database_name = "hybrid-orchestrator-main"
database_id = "32d0ab8a-43b7-46a3-bf4c-7f10ebc5d19b"

[[d1_databases]]
binding = "ANALYTICS_DB"
database_name = "sina-analytics-dashboard"
database_id = "92d60ed2-b370-4d6d-ac16-a309175d4392"

[[d1_databases]]
binding = "AUTH_DB"
database_name = "sina-user-authentication"
database_id = "6dcb67ed-9898-4e77-9d10-c4fd97aaeb6c"

[[d1_databases]]
binding = "CONTRACTS_DB"
database_name = "sina-contracts-governance"
database_id = "442af523-8dc3-423b-ba20-c8a5206d2d4d"

[[d1_databases]]
binding = "CREDIBILITY_DB"
database_name = "sina-credibility-automation"
database_id = "ebc5de10-b0a7-4727-8cc5-97fb9c41c5a3"

[[d1_databases]]
binding = "GOV_ACCESS_DB"
database_name = "government-accessibility-focus"
database_id = "7839cf37-1d3c-411f-b0b3-f6c6912cc96c"

[[d1_databases]]
binding = "CHAT_HISTORY_DB"
database_name = "claude-chat-history"
database_id = "451fdafa-5458-4a98-9439-44fe2e2077c7"

# Durable Objects (SQLite classes for free plan)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["AgentController"]

[durable_objects]
bindings = [
  { name = "AGENT_CONTROLLER", class_name = "AgentController" }
]

# Global compatibility flags (keep minimal)
compatibility_flags = []

# Base environment variables (use secrets for anything sensitive)
[vars]
ENVIRONMENT = "production"
SYSTEM_VERSION = "3.0.0"
DEPLOYMENT_DATE = "2025-09-20"
CLOUDFLARE_PRO_PRICE = "25"
DAILY_EARNING_TARGET = "0.1"
MIN_WITHDRAWAL = "0.01"
MAX_REQUESTS_PER_MINUTE = "60"
BURST_LIMIT = "10"
ENABLE_AUTO_EARN = "true"
ENABLE_CRYPTO_GATEWAY = "true"
ENABLE_AI_ASSISTANCE = "true"
ENABLE_VOICE_COMMANDS = "false"
STRIPE_WEBHOOK_ENDPOINT = "https://sina-empire-stripe-production.workers.dev/webhook"
CRYPTO_GATEWAY_ENDPOINT = "https://sina-empire-crypto-gateway.workers.dev/api"
ENABLE_BOT_PROTECTION = "true"
ENABLE_DDOS_PROTECTION = "true"
REQUIRE_API_KEY = "true"

# Development environment
[env.development]
name = "sina-empire-revenue-dev"
[env.development.vars]
ENVIRONMENT = "development"
ENABLE_DEBUG = "true"
SYSTEM_VERSION = "3.0.0"
ENABLE_AUTO_EARN = "false"
REQUIRE_API_KEY = "false"
[[env.development.kv_namespaces]]
binding = "EARNINGS_KV"
id = "9ca5fa02e54a4ec3b0e77243ba842608"

# Staging environment
[env.staging]
name = "sina-empire-revenue-staging"
[env.staging.vars]
ENVIRONMENT = "staging"
ENABLE_DEBUG = "false"
SYSTEM_VERSION = "3.0.0"
ENABLE_AUTO_EARN = "true"
REQUIRE_API_KEY = "true"

# Production environment
[env.production]
name = "sina-empire-revenue-multiplier"
usage_model = "unbound"
[env.production.triggers]
crons = ["*/5 * * * *"]
[env.production.durable_objects]
bindings = [
  { name = "AGENT_CONTROLLER", class_name = "AgentController" }
]
[env.production.vars]
ENVIRONMENT = "production"
ENABLE_DEBUG = "false"
SYSTEM_VERSION = "3.0.0"
DEPLOYMENT_DATE = "2025-09-20"
CLOUDFLARE_PRO_PRICE = "25"
DAILY_EARNING_TARGET = "0.1"
MIN_WITHDRAWAL = "0.01"
MAX_REQUESTS_PER_MINUTE = "60"
BURST_LIMIT = "10"
ENABLE_AUTO_EARN = "true"
ENABLE_CRYPTO_GATEWAY = "true"
ENABLE_AI_ASSISTANCE = "true"
ENABLE_VOICE_COMMANDS = "false"
STRIPE_WEBHOOK_ENDPOINT = "https://sina-empire-stripe-production.workers.dev/webhook"
CRYPTO_GATEWAY_ENDPOINT = "https://sina-empire-crypto-gateway.workers.dev/api"
ENABLE_BOT_PROTECTION = "true"
ENABLE_DDOS_PROTECTION = "true"
REQUIRE_API_KEY = "true"

# Note: set sensitive values with `wrangler secret put` before deploying:
# ADMIN_TOKEN, CHANGENOW_API_KEY, ALCHEMY_API_KEY, CLOUDFLARE_API_TOKEN


# API endpoints
STRIPE_WEBHOOK_ENDPOINT = "https://sina-empire-stripe-production.workers.dev/webhook"
CRYPTO_GATEWAY_ENDPOINT = "https://sina-empire-crypto-gateway.workers.dev/api"

# Security
ENABLE_BOT_PROTECTION = "true"
ENABLE_DDOS_PROTECTION = "true"
REQUIRE_API_KEY = "false"

# Development environment (for local testing)
[env.development]
name = "sina-empire-revenue-dev"
vars = { ENVIRONMENT = "development", ENABLE_DEBUG = "true" }
kv_namespaces = [
  { binding = "EARNINGS_KV", id = "9ca5fa02e54a4ec3b0e77243ba842608", preview_id = "9ca5fa02e54a4ec3b0e77243ba842608" }
]

# Staging environment
[env.staging]
name = "sina-empire-revenue-staging"
vars = { ENVIRONMENT = "staging", ENABLE_DEBUG = "false" }

# Production environment (explicit)
[env.production]
name = "sina-empire-revenue-multiplier"
usage_model = "unbound"  # Recommended for production (post-Pro upgrade for extended CPU)

kv_namespaces = [
  { binding = "EARNINGS_KV", id = "9ca5fa02e54a4ec3b0e77243ba842608" },
  { binding = "EMPIRE_CACHE", id = "1164fb667ae0464898de97d1f563886d" },
  { binding = "EMPIRE_CONTEXT", id = "36117b73cef941659257140e7066b5f7" },
  { binding = "SINA_CACHE", id = "cf19a78186ad42aba2bb76d7b34de672" },
  { binding = "SINA_EMPIRE_KV", id = "09aae939bc894cf1a15220fe828865f2" },
  { binding = "AUTOMATION_KV", id = "4d77c10ba1354134b6802a2de55f52f8" },
  { binding = "WEBHOOKS_KV", id = "3bbcd308d5b445e7bac902c55306ad3a" },
  { binding = "SECURITY_POLICIES", id = "0fef29570fca4fec977c43f33a856666" },
  { binding = "API_KEYS", id = "2b06bf375a9e4e82931a55f1a5fb6aff" },
  { binding = "MONITORING_CACHE", id = "34acb1e1a4a845c7931e8a6c67cd7344" },
  { binding = "ORCHESTRATOR_STATE", id = "1d1359f07ebf484e858d42445149be74" },
  { binding = "DEPLOYMENT_META", id = "5a8e7f12fa8e4868b72c9e5a03f6c04c" },
  { binding = "STRIPE_CONFIG", id = "8e96840961cb4a35b60425997d299cda" },
  { binding = "STRIPE_CACHE", id = "a8671847d0b147a3b897caac2a39c05e" },
  { binding = "VOICE_STORAGE", id = "7af1a98ea8054237af880f3bb7d5248f" },
  { binding = "AI_SESSIONS", id = "a962fb6328dc4e3ca4950ada17a5bc3d" },
  { binding = "CLAUDE_SESSIONS", id = "c87f7299cfae4bd08e54dcfab3d473e2" },
  { binding = "GEMINI_SESSIONS", id = "ba0452110d274dd19d4b32b2f20c0914" },
  { binding = "SUPPLIER_INTEL", id = "5c60237afd5f4b9bacb84d7be8a6d588" },
  { binding = "GENEALOGY_DATA", id = "59694d39d35e47f398f5cc3db8d35d80" }
]

# Durable Objects migrations (global, required for free plan)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["AgentController"]

# Global Durable Objects bindings (can be overridden per env)
[durable_objects]
bindings = [
  { name = "AGENT_CONTROLLER", class_name = "AgentController" }
]

# Global cron triggers (overridable per env)
[triggers]
crons = ["*/5 * * * *"]  # Every 5 minutes

[env.production.vars]
SYSTEM_VERSION = "1.0.1-fixed"
DEPLOYMENT_DATE = "2025-09-20"
# ADMIN_TOKEN must be set via `wrangler secret put ADMIN_TOKEN --env production`
# Do NOT store secrets in this file. Set the admin token with Wrangler before deploy.
ADMIN_TOKEN = ""
CLOUDFLARE_PRO_PRICE = "25"
DAILY_EARNING_TARGET = "5"
MIN_WITHDRAWAL = "0.1"
MAX_REQUESTS_PER_MINUTE = "60"
BURST_LIMIT = "10"
ENABLE_AUTO_EARN = "true"
ENABLE_CRYPTO_GATEWAY = "true"
ENABLE_AI_ASSISTANCE = "true"
ENABLE_VOICE_COMMANDS = "false"
STRIPE_WEBHOOK_ENDPOINT = "/api/stripe-webhook"
CRYPTO_GATEWAY_ENDPOINT = "/api/crypto-webhook"
ENABLE_BOT_PROTECTION = "true"
ENABLE_DDOS_PROTECTION = "true"
REQUIRE_API_KEY = "true"
ENVIRONMENT = "production"
ENABLE_DEBUG = "false"

[env.staging]
name = "sina-empire-revenue-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
ENABLE_DEBUG = "false"
SYSTEM_VERSION = "3.0.0"
ENABLE_AUTO_EARN = "true"
REQUIRE_API_KEY = "true"

[env.production]
name = "sina-empire-revenue-multiplier"
usage_model = "unbound"  # Recommended for production (post-Pro upgrade for extended CPU)

kv_namespaces = [
  { binding = "EARNINGS_KV", id = "9ca5fa02e54a4ec3b0e77243ba842608" },
  { binding = "EMPIRE_CACHE", id = "1164fb667ae0464898de97d1f563886d" },
  { binding = "EMPIRE_CONTEXT", id = "36117b73cef941659257140e7066b5f7" },
  { binding = "SINA_CACHE", id = "cf19a78186ad42aba2bb76d7b34de672" },
  { binding = "SINA_EMPIRE_KV", id = "09aae939bc894cf1a15220fe828865f2" },
  { binding = "AUTOMATION_KV", id = "4d77c10ba1354134b6802a2de55f52f8" },
  { binding = "WEBHOOKS_KV", id = "3bbcd308d5b445e7bac902c55306ad3a" },
  { binding = "SECURITY_POLICIES", id = "0fef29570fca4fec977c43f33a856666" },
  { binding = "API_KEYS", id = "2b06bf375a9e4e82931a55f1a5fb6aff" },
  { binding = "MONITORING_CACHE", id = "34acb1e1a4a845c7931e8a6c67cd7344" },
  { binding = "ORCHESTRATOR_STATE", id = "1d1359f07ebf484e858d42445149be74" },
  { binding = "DEPLOYMENT_META", id = "5a8e7f12fa8e4868b72c9e5a03f6c04c" },
  { binding = "STRIPE_CONFIG", id = "8e96840961cb4a35b60425997d299cda" },
  { binding = "STRIPE_CACHE", id = "a8671847d0b147a3b897caac2a39c05e" },
  { binding = "VOICE_STORAGE", id = "7af1a98ea8054237af880f3bb7d5248f" },
  { binding = "AI_SESSIONS", id = "a962fb6328dc4e3ca4950ada17a5bc3d" },
  { binding = "CLAUDE_SESSIONS", id = "c87f7299cfae4bd08e54dcfab3d473e2" },
  { binding = "GEMINI_SESSIONS", id = "ba0452110d274dd19d4b32b2f20c0914" },
  { binding = "SUPPLIER_INTEL", id = "5c60237afd5f4b9bacb84d7be8a6d588" },
  { binding = "GENEALOGY_DATA", id = "59694d39d35e47f398f5cc3db8d35d80" }
]

# Durable Objects migrations (global, required for free plan)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["AgentController"]

# Global Durable Objects bindings (can be overridden per env)
[durable_objects]
bindings = [
  { name = "AGENT_CONTROLLER", class_name = "AgentController" }
]

# Global cron triggers (overridable per env)
[triggers]
crons = ["*/5 * * * *"]  # Every 5 minutes

[env.production.vars]
SYSTEM_VERSION = "1.0.1-fixed"
DEPLOYMENT_DATE = "2025-09-20"
ADMIN_TOKEN = "EMPIRE_ADMIN_2024_SECURE"
CLOUDFLARE_PRO_PRICE = "25"
DAILY_EARNING_TARGET = "5"
MIN_WITHDRAWAL = "0.1"
MAX_REQUESTS_PER_MINUTE = "60"
BURST_LIMIT = "10"
ENABLE_AUTO_EARN = "true"
ENABLE_CRYPTO_GATEWAY = "true"
ENABLE_AI_ASSISTANCE = "true"
ENABLE_VOICE_COMMANDS = "false"
STRIPE_WEBHOOK_ENDPOINT = "/api/stripe-webhook"
CRYPTO_GATEWAY_ENDPOINT = "/api/crypto-webhook"
ENABLE_BOT_PROTECTION = "true"
ENABLE_DDOS_PROTECTION = "true"
REQUIRE_API_KEY = "true"
ENVIRONMENT = "production"
ENABLE_DEBUG = "false"
